// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnmpxyayctbojqcqhwjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdubXB4eWF5Y3Rib2pxY3Fod2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MjU0NjUsImV4cCI6MjA2ODQwMTQ2NX0.cyhxMofhe2Qf3tuwAhW3wBpRhT-cqBODTmxHKvqY4_A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});